### ISSUE TITLE
我是这种报错，请问这是什么问题呀

### ISSUE THREAD

**Issue by MrBaiLiJie** [Cansiny0320/book-spider#3]
![image](https://user-images.githubusercontent.com/40562894/143672909-dbbf08f1-f595-4dab-99f0-3eaf0a7ff7fb.png)
![image](https://user-images.githubusercontent.com/40562894/143672917-46647974-0d6a-4c53-87dd-1d80a8218188.png)

**Comment by Cansiny0320** [comment]
类型问题 已修复

**Comment by MrBaiLiJie** [comment]
![image](https://user-images.githubusercontent.com/40562894/143796961-9d7f602b-e19b-4c09-b9a1-fb09352ab79a.png)
还是不可以，请问这是什么问题

**Comment by Cansiny0320** [comment]
> ![image](https://user-images.githubusercontent.com/40562894/143796961-9d7f602b-e19b-4c09-b9a1-fb09352ab79a.png) 还是不可以，请问这是什么问题

你的 node 版本太低 建议更新到 v16 版本
